export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const CHANGE_LOADER = "CHANGE LOADER";
export const ERROR_FETCHING_PERSONS = "ERROR_FETCHING_PERSONS";
export const PERSON_QUOTE = "PERSON_QUOTE";
export const IS_LOADING_QUOTE = "IS_LOADING_QUOTE";
export const IS_ERROR_QUOTE = "IS_ERROR_QUOTE"
